In [10]:
#slicing
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
slice1=arr[2:6]
print(slice1)
#slicing with step of 2
slice2=arr[::2]
print(slice2)

[3 4 5 6]
[1 3 5 7 9]


In [11]:
#reversed array
rev=arr[::-1]
print(rev)

[9 8 7 6 5 4 3 2 1]


In [25]:
#slicing multi-dimensional array
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
#slice rows 0 to 2, col 1 to 3
sub=a[0:2,1:3]
print(sub)
#extract 1st column
col=a[:,0]
print(col)
#extract 1st row
row=a[0,:]
print(row)

[[2 3]
 [5 6]]
[1 4 7]
[1 2 3]


In [24]:
#printing element based on index
print(a[0,0])
print(a[1,2])
print(a[1,1])

1
6
5


In [27]:
#basic indexing
arr=np.array([10,20,30,40,50])
print(arr[1])
print(arr[-1])

20
50


In [29]:
#subset indexing
print(arr[1:4])

[20 30 40]


In [32]:
#printing element based on a condition
print(arr[arr>25])

[30 40 50]


In [35]:
#horizontal and vertical join
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
print(np.hstack((arr1,arr2)))
print(np.vstack((arr1,arr2)))

[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [36]:
#depth join
print(np.dstack((arr1,arr2)))

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [48]:
#splitting in numpy
a=np.array([1,2,3,4,5,6])
print(np.split(a,2))


[array([1, 2, 3]), array([4, 5, 6])]


In [50]:
print(np.array_split(a,4))

[array([1, 2]), array([3, 4]), array([5]), array([6])]
